USE [ProjektMPK]

DROP TABLE [dbo].[Kierowcy_autobusow]
DROP TABLE [dbo].[Motorniczy]
DROP TABLE [dbo].[Tramwaje]
DROP TABLE [dbo].[Autobusy]
DROP TABLE [dbo].[Godziny_pracy]
DROP TABLE [dbo].[Pracownicy]
DROP TABLE [dbo].[Pojazdy]
DROP TABLE [dbo].[Godziny_odjazdow]
DROP TABLE [dbo].[Opis_trasy]
DROP TABLE [dbo].[Relacje]
DROP TABLE [dbo].[Linie]
DROP TABLE [dbo].[Przystanki]
DROP TABLE [dbo].[Poziomy_uprawnien]