USE ProjektMPK;

INSERT INTO Poziomy_uprawnien VALUES('Zwykly');
INSERT INTO Poziomy_uprawnien VALUES('Krakowiak');
INSERT INTO Poziomy_uprawnien VALUES('Lajkonik');

EXEC Wstaw_motorniczego Paulina, Sobczak, K, 2
EXEC Wstaw_motorniczego Henryk, Bak, M, 1
EXEC Wstaw_motorniczego Kazimierz, Gorski, M, 2
EXEC Wstaw_motorniczego Irena, Wojcik, K, 2
EXEC Wstaw_motorniczego Marian, Chmielewski, M, 3
EXEC Wstaw_motorniczego Malgorzata, Jaworska, K, 3
EXEC Wstaw_motorniczego Ewa, Duda, K, 2
EXEC Wstaw_motorniczego Jakub, Malinowski, M, 3
EXEC Wstaw_motorniczego Jadwiga, Brzezinska, K, 2
EXEC Wstaw_motorniczego Roman, Sawicki, M, 2
EXEC Wstaw_motorniczego Marcin, Szymczak, M, 3
EXEC Wstaw_motorniczego Joanna, Baranowska, K, 1
EXEC Wstaw_motorniczego Maciej, Szczepanski, M, 3
EXEC Wstaw_motorniczego Czeslaw, Wrobel, M, 3
EXEC Wstaw_motorniczego Grazyna, Gorska, K, 2
EXEC Wstaw_motorniczego Wanda, Krawczyk, K, 2
EXEC Wstaw_motorniczego Renata, Urbanska, K, 2
EXEC Wstaw_motorniczego Wieslawa, Tomaszewska, K, 2
EXEC Wstaw_motorniczego Bozena, Baranowska, K, 1
EXEC Wstaw_motorniczego Ewelina, Malinowska, K, 1
EXEC Wstaw_motorniczego Anna, Krajewska, K, 2
EXEC Wstaw_motorniczego Mieczyslaw, Zajac, M, 1
EXEC Wstaw_motorniczego Wieslaw, Przybylski, M, 2
EXEC Wstaw_motorniczego Dorota, Tomaszewska, K, 2
EXEC Wstaw_motorniczego Jerzy, Wroblewski, M, 1
EXEC Wstaw_motorniczego Magdalena, Adamczyk, K, 2
EXEC Wstaw_motorniczego Wladyslaw, Piotrowski, M, 2
EXEC Wstaw_motorniczego Marek, Wisniewski, M, 2
EXEC Wstaw_motorniczego Stanislawa, Glowacka, K, 1
EXEC Wstaw_motorniczego Agata, Kubiak, K, 3
EXEC Wstaw_motorniczego Marian, Kowalski, M, 1
EXEC Wstaw_motorniczego Piotr, Szymanski, M, 2
EXEC Wstaw_motorniczego Stanislaw, Kowalski, M, 2
EXEC Wstaw_motorniczego Aleksandra, Szulc, K, 2
EXEC Wstaw_motorniczego Tomasz, Kucharski, M, 3
EXEC Wstaw_motorniczego Marcin, Mazurek, M, 3
EXEC Wstaw_motorniczego Sebastian, Baranowski, M, 2
EXEC Wstaw_motorniczego Agata, Wysocka, K, 2
EXEC Wstaw_motorniczego Grazyna, Mazur, K, 3
EXEC Wstaw_motorniczego Marcin, Gajewski, M, 2
EXEC Wstaw_motorniczego Krystyna, Sikorska, K, 2
EXEC Wstaw_motorniczego Krzysztof, Kowalski, M, 2
EXEC Wstaw_motorniczego Malgorzata, Mazurek, K, 1
EXEC Wstaw_motorniczego Adam, Jasinski, M, 2
EXEC Wstaw_motorniczego Patrycja, Makowska, K, 2
EXEC Wstaw_motorniczego Piotr, Adamczyk, M, 3
EXEC Wstaw_motorniczego Waldemar, Wieczorek, M, 3
EXEC Wstaw_motorniczego Edward, Szulc, M, 2
EXEC Wstaw_motorniczego Janusz, Andrzejewski, M, 2
EXEC Wstaw_motorniczego Edyta, Nowakowska, K, 1
EXEC Wstaw_kierowce Joanna, Wozniak, K, 2
EXEC Wstaw_kierowce Mateusz, Michalak, M, 2
EXEC Wstaw_kierowce Marta, Sobczak, K, 1
EXEC Wstaw_kierowce Waldemar, Makowski, M, 1
EXEC Wstaw_kierowce Marzena, Jablonska, K, 2
EXEC Wstaw_kierowce Maciej, Sikora, M, 2
EXEC Wstaw_kierowce Monika, Szewczyk, K, 1
EXEC Wstaw_kierowce Genowefa, Cieslak, K, 2
EXEC Wstaw_kierowce Edyta, Nowicka, K, 1
EXEC Wstaw_kierowce Piotr, Malinowski, M, 3
EXEC Wstaw_kierowce Krzysztof, Glowacki, M, 2
EXEC Wstaw_kierowce Andrzej, Szewczyk, M, 3
EXEC Wstaw_kierowce Mariusz, Grabowski, M, 3
EXEC Wstaw_kierowce Stefania, Krol, K, 3
EXEC Wstaw_kierowce Wieslaw, Szczepanski, M, 3
EXEC Wstaw_kierowce Malgorzata, Wasilewska, K, 2
EXEC Wstaw_kierowce Jozef, Szczepanski, M, 3
EXEC Wstaw_kierowce Mariusz, Kowalczyk, M, 1
EXEC Wstaw_kierowce Janina, Kozlowska, K, 1
EXEC Wstaw_kierowce Roman, Kwiatkowski, M, 1
EXEC Wstaw_kierowce Jadwiga, Kaminska, K, 3
EXEC Wstaw_kierowce Agnieszka, Zajac, K, 2
EXEC Wstaw_kierowce Robert, Wlodarczyk, M, 3
EXEC Wstaw_kierowce Henryk, Kowalski, M, 1
EXEC Wstaw_kierowce Kazimiera, Zalewska, K, 1
EXEC Wstaw_kierowce Sylwia, Kazmierczak, K, 2
EXEC Wstaw_kierowce Dorota, Maciejewska, K, 3
EXEC Wstaw_kierowce Jacek, Laskowski, M, 1
EXEC Wstaw_kierowce Michal, Sobczak, M, 3
EXEC Wstaw_kierowce Genowefa, Lis, K, 3
EXEC Wstaw_kierowce Miroslaw, Czerwinski, M, 3
EXEC Wstaw_kierowce Agata, Gajewska, K, 1
EXEC Wstaw_kierowce Zofia, Bak, K, 1
EXEC Wstaw_kierowce Marek, Adamczyk, M, 3
EXEC Wstaw_kierowce Agata, Pawlak, K, 3
EXEC Wstaw_kierowce Adam, Jankowski, M, 2
EXEC Wstaw_kierowce Mieczyslaw, Adamczyk, M, 3
EXEC Wstaw_kierowce Wanda, Czarnecka, K, 1
EXEC Wstaw_kierowce Andrzej, Ziolkowski, M, 1
EXEC Wstaw_kierowce Jaroslaw, Laskowski, M, 3
EXEC Wstaw_kierowce Iwona, Urbanska, K, 3
EXEC Wstaw_kierowce Aneta, Jakubowska, K, 3
EXEC Wstaw_kierowce Zdzislaw, Krol, M, 3
EXEC Wstaw_kierowce Maria, Wisniewska, K, 2
EXEC Wstaw_kierowce Grzegorz, Borkowski, M, 2
EXEC Wstaw_kierowce Maria, Glowacka, K, 3
EXEC Wstaw_kierowce Jakub, Pietrzak, M, 1
EXEC Wstaw_kierowce Danuta, Piotrowska, K, 1
EXEC Wstaw_kierowce Sebastian, Chmielewski, M, 3
EXEC Wstaw_kierowce Adam, Andrzejewski, M, 1

EXEC Wstaw_tramwaj KWADRACIAK0, 1
EXEC Wstaw_tramwaj KWADRACIAK1, 1
EXEC Wstaw_tramwaj KWADRACIAK2, 1
EXEC Wstaw_tramwaj KWADRACIAK3, 1
EXEC Wstaw_tramwaj KWADRACIAK4, 1
EXEC Wstaw_tramwaj KWADRACIAK5, 1
EXEC Wstaw_tramwaj KWADRACIAK6, 1
EXEC Wstaw_tramwaj KWADRACIAK7, 1
EXEC Wstaw_tramwaj KWADRACIAK8, 1
EXEC Wstaw_tramwaj KWADRACIAK9, 1
EXEC Wstaw_tramwaj KWADRACIAK10, 1
EXEC Wstaw_tramwaj LAJKONIK11, 2
EXEC Wstaw_tramwaj LAJKONIK12, 2
EXEC Wstaw_tramwaj LAJKONIK13, 2
EXEC Wstaw_tramwaj LAJKONIK14, 2
EXEC Wstaw_tramwaj LAJKONIK15, 2
EXEC Wstaw_tramwaj LAJKONIK16, 2
EXEC Wstaw_tramwaj LAJKONIK17, 2
EXEC Wstaw_tramwaj LAJKONIK18, 2
EXEC Wstaw_tramwaj LAJKONIK19, 2
EXEC Wstaw_tramwaj LAJKONIK20, 2
EXEC Wstaw_tramwaj KRAKOWIAK21, 3
EXEC Wstaw_tramwaj KRAKOWIAK22, 3
EXEC Wstaw_tramwaj KRAKOWIAK23, 3
EXEC Wstaw_tramwaj KRAKOWIAK24, 3
EXEC Wstaw_tramwaj KRAKOWIAK25, 3
EXEC Wstaw_tramwaj KRAKOWIAK26, 3
EXEC Wstaw_tramwaj KRAKOWIAK27, 3
EXEC Wstaw_tramwaj KRAKOWIAK28, 3
EXEC Wstaw_tramwaj KRAKOWIAK29, 3
EXEC Wstaw_tramwaj KRAKOWIAK30, 3
EXEC Wstaw_autobus SOLARIS0, 0
EXEC Wstaw_autobus SOLARIS1, 0
EXEC Wstaw_autobus SOLARIS2, 0
EXEC Wstaw_autobus SOLARIS3, 0
EXEC Wstaw_autobus SOLARIS4, 0
EXEC Wstaw_autobus SOLARIS5, 0
EXEC Wstaw_autobus SOLARIS6, 0
EXEC Wstaw_autobus SOLARIS7, 0
EXEC Wstaw_autobus SOLARIS8, 0
EXEC Wstaw_autobus SOLARIS9, 0
EXEC Wstaw_autobus SOLARIS10, 0
EXEC Wstaw_autobus MERCEDES11, 0
EXEC Wstaw_autobus MERCEDES12, 0
EXEC Wstaw_autobus MERCEDES13, 0
EXEC Wstaw_autobus MERCEDES14, 0
EXEC Wstaw_autobus MERCEDES15, 0
EXEC Wstaw_autobus MERCEDES16, 0
EXEC Wstaw_autobus MERCEDES17, 0
EXEC Wstaw_autobus MERCEDES18, 0
EXEC Wstaw_autobus MERCEDES19, 0
EXEC Wstaw_autobus MERCEDES20, 0
EXEC Wstaw_autobus ELECTRON21, 1
EXEC Wstaw_autobus ELECTRON22, 1
EXEC Wstaw_autobus ELECTRON23, 1
EXEC Wstaw_autobus ELECTRON24, 1
EXEC Wstaw_autobus ELECTRON25, 1
EXEC Wstaw_autobus ELECTRON26, 1
EXEC Wstaw_autobus ELECTRON27, 1
EXEC Wstaw_autobus ELECTRON28, 1
EXEC Wstaw_autobus ELECTRON29, 1
EXEC Wstaw_autobus ELECTRON30, 1

INSERT INTO Linie
VALUES
	( 1, 1 ),
	( 2, 1 ),
	( 4, 1 ),
	( 8, 1 ),
	( 10, 1 ),
	( 14, 1 ),
	( 16, 1 ),
	( 18, 1 ),
	( 20, 1 ),
	( 21, 1 ),
	( 22, 1 ),
	( 52, 1 ),
	( 70, 1 ),
	( 71, 1 ),
	( 72, 1 ),
	( 73, 1 ),
	( 74, 1 ),
	( 75, 1 ),
	( 76, 1 ),
	( 77, 1 ),
	( 78, 1 ),
	( 79, 1 ),
	( 62, 1 ),
	( 64, 1 ),
	( 69, 1 ),
	( 100, 0 ),
	( 101, 0 ),
	( 102, 0 ),
	( 105, 0 ),
	( 106, 0 ),
	( 107, 0 ),
	( 109, 0 ),
	( 110, 0 ),
	( 111, 0 ),
	( 112, 0 ),
	( 113, 0 ),
	( 115, 0 ),
	( 117, 0 ),
	( 118, 0 ),
	( 120, 0 ),
	( 122, 0 ),
	( 123, 0 ),
	( 124, 0 ),
	( 125, 0 ),
	( 127, 0 ),
	( 128, 0 ),
	( 129, 0 ),
	( 130, 0 ),
	( 131, 0 ),
	( 132, 0 ),
	( 133, 0 ),
	( 134, 0 ),
	( 135, 0 ),
	( 137, 0 ),
	( 138, 0 ),
	( 139, 0 ),
	( 141, 0 ),
	( 142, 0 ),
	( 143, 0 ),
	( 144, 0 ),
	( 145, 0 ),
	( 151, 0 ),
	( 152, 0 ),
	( 153, 0 ),
	( 154, 0 ),
	( 155, 0 ),
	( 158, 0 ),
	( 159, 0 ),
	( 161, 0 ),
	( 162, 0 ),
	( 163, 0 ),
	( 164, 0 ),
	( 166, 0 ),
	( 168, 0 ),
	( 171, 0 ),
	( 172, 0 ),
	( 173, 0 ),
	( 174, 0 ),
	( 175, 0 ),
	( 178, 0 ),
	( 179, 0 ),
	( 181, 0 ),
	( 182, 0 ),
	( 183, 0 ),
	( 184, 0 ),
	( 193, 0 ),
	( 194, 0 ),
	( 201, 0 ),
	( 202, 0 ),
	( 203, 0 ),
	( 204, 0 ),
	( 207, 0 ),
	( 208, 0 ),
	( 209, 0 ),
	( 210, 0 ),
	( 211, 0 ),
	( 212, 0 ),
	( 213, 0 ),
	( 214, 0 ),
	( 215, 0 ),
	( 217, 0 ),
	( 218, 0 ),
	( 220, 0 ),
	( 221, 0 ),
	( 222, 0 ),
	( 223, 0 ),
	( 225, 0 ),
	( 226, 0 ),
	( 227, 0 ),
	( 229, 0 ),
	( 230, 0 ),
	( 232, 0 ),
	( 233, 0 ),
	( 234, 0 ),
	( 235, 0 ),
	( 237, 0 ),
	( 238, 0 ),
	( 239, 0 ),
	( 240, 0 ),
	( 242, 0 ),
	( 243, 0 ),
	( 244, 0 ),
	( 245, 0 ),
	( 247, 0 ),
	( 248, 0 ),
	( 249, 0 ),
	( 250, 0 ),
	( 252, 0 ),
	( 253, 0 ),
	( 255, 0 ),
	( 257, 0 ),
	( 258, 0 ),
	( 259, 0 ),
	( 260, 0 ),
	( 263, 0 ),
	( 265, 0 ),
	( 267, 0 ),
	( 268, 0 ),
	( 269, 0 ),
	( 270, 0 ),
	( 273, 0 ),
	( 275, 0 ),
	( 277, 0 ),
	( 278, 0 ),
	( 280, 0 ),
	( 283, 0 ),
	( 285, 0 ),
	( 287, 0 ),
	( 292, 0 ),
	( 297, 0 ),
	( 301, 0 ),
	( 304, 0 ),
	( 352, 0 ),
	( 405, 0 ),
	( 412, 0 ),
	( 422, 0 ),
	( 424, 0 ),
	( 451, 0 ),
	( 482, 0 ),
	( 501, 0 ),
	( 502, 0 ),
	( 503, 0 ),
	( 572, 0 ),
	( 601, 0 ),
	( 605, 0 ),
	( 608, 0 ),
	( 610, 0 ),
	( 618, 0 ),
	( 637, 0 ),
	( 642, 0 ),
	( 643, 0 ),
	( 703, 0 ),
	( 706, 0 ),
	( 714, 0 ),
	( 769, 0 ),
	( 774, 0 ),
	( 902, 0 ),
	( 903, 0 ),
	( 904, 0 );


INSERT INTO Przystanki
VALUES
( 'Wysiolek Luborzycki Radwany' ),
( 'Przeginia Duchowna Szkola' ),
( 'Os.Podwawelskie' ),
( 'Czerwiakowskiego' ),
( 'AGH' ),
( 'Pod Fortem' ),
( 'Niepolomice Jazy' ),
( 'Zakamycze' ),
( 'Stachiewicza' ),
( 'Skawina Korabnicka Szkola' ),
( 'Popielidow' ),
( 'Podleze Centrum' ),
( 'Pachonskiego' ),
( 'Wegrzce' ),
( 'Niepolomice Pasternik' ),
( 'Ochodza Odwisle' ),
( 'Fort Swoszowice' ),
( 'Brzezinka Skrzyzowanie' ),
( 'Krasieniec Zakupny' ),
( 'EC leg' ),
( 'Grabie Szczurow' ),
( 'Dajwor' ),
( 'Os.Piastow' ),
( 'Michalowice Ujecie Wody' ),
( 'Dworzec Glowny Tunel' ),
( 'Pielgrzymowice I' ),
( 'Rudawa Bloki' ),
( 'Waly Wislane' ),
( 'Ochmanow Otaczarnia' ),
( 'Rybna Osrodek Zdrowia' ),
( 'Tuchowska' ),
( 'Wieczysta' ),
( 'Droga do Rzaski' ),
( 'Michalowice Kwiaty Polne' ),
( 'Glinnik' ),
( 'Owczary' ),
( 'Dwor Czeczow' ),
( 'swiatniki Skrzyzowanie' ),
( 'Kaszow lysa Gora' ),
( 'Tyniecka Autostrada' ),
( 'Stopien Wodny' ),
( 'Mochnaniec' ),
( 'Os.Oswiecenia' ),
( 'Lubostron' ),
( 'Zastow' ),
( 'Os.Kalinowe' ),
( 'Lipska' ),
( 'Polana zywiecka' ),
( 'Gorskie Domy' ),
( 'Wiktorowice Skrzyzowanie' ),
( 'Niepolomice Kolejowa' ),
( 'Bielany Klasztor' ),
( 'Wyzral I' ),
( 'Nielepice' ),
( 'Konczyce' ),
( 'Myslenicka' ),
( 'Podgaje' ),
( 'Na Zaleczu Szkola' ),
( 'Swoszowice' ),
( 'Krzyszkowice Kasztanowa I' ),
( 'Niepolomice Boryczow' ),
( 'Zielonki Skrzyzowanie' ),
( 'Dlubnia' ),
( 'Biezanow Drozdzownia PKP' ),
( 'Laskowiec' ),
( 'Starowislna' ),
( 'lokietka' ),
( 'Os.Kolorowe' ),
( 'Konary' ),
( 'Sielanka' ),
( 'Os.Wandy' ),
( 'Surzyckiego' ),
( 'Wyciaze Wiadukt' ),
( 'Kobylany I' ),
( 'Rzeszotary Zalesie' ),
( 'Rudawa Kosciol' ),
( 'Wydzial Farmaceutyczny UJ' ),
( 'Batowice PKP' ),
( 'Szyce I' ),
( 'Gorka Narodowa Wschod' ),
( 'Ksiazniczki Boisko' ),
( 'Skawina Tyniecka Osiedle' ),
( 'Brzeznica Pasieka' ),
( 'Chelmska' ),
( 'Maszyce II' ),
( 'Petöfiego' ),
( 'Czulow I' ),
( 'Zachodnia' ),
( 'Lusina Dwor' ),
( 'Budzyn Plaza Glowna' ),
( 'Medweckiego' ),
( 'Goluchowice' ),
( 'Nalkowskiej' ),
( 'Imbramowska' ),
( 'slaskiego' ),
( 'Wroblowice Dom Kultury' ),
( 'Struga' ),
( 'Pedzichow' ),
( 'Rzeszotary Pod Debina' ),
( 'Skala Kmity' ),
( 'Teatr Ludowy' ),
( 'Sadowie' ),
( 'Radzikowskiego Osiedle' ),
( 'Rondo Matecznego' ),
( 'Pielgrzymowice' ),
( 'Wola Radziszowska Centrum' ),
( 'Bagienna' ),
( 'Ojcowska Wagroda' ),
( 'Bohomolca' ),
( 'Kopanka' ),
( 'Wyzral Szkola' ),
( 'Nowohucka' ),
( 'Zabierzow Osrodek Zdrowia' ),
( 'Libertow Szkola' ),
( 'Michalowice Osrodek Zdrowia' ),
( 'Wegrzce Centrum' ),
( 'Slomczynskiego' ),
( 'Wrony' ),
( 'Skawina Sad' ),
( 'Polanka Hallera Dwor' ),
( 'Podskale' ),
( 'Wadow Osiedle' ),
( 'Wieliczka CPN' ),
( 'Koszykarska' ),
( 'Motyla' ),
( 'Chrosna' ),
( 'Korzkiew I' ),
( 'Przybyslawice II' ),
( 'lososkowice Szkola' ),
( 'Narzymskiego' ),
( 'Granica Miasta' ),
( 'Wolowice Sklep' ),
( 'Makuszynskiego' ),
( 'Kapelanka' ),
( 'Droga do Sidziny' ),
( 'Bratyslawska' ),
( 'Azory' ),
( 'Kawiory' ),
( 'Narama' ),
( 'Zakepie' ),
( 'Slomiana' ),
( 'Wolowice Niwa' ),
( 'Jaskowice' ),
( 'Wolica Las' ),
( 'M1 Al. Pokoju' ),
( 'Kapielowa' ),
( 'Rybna Dol' ),
( 'Raczna Dzikowiec' ),
( 'Bora-Komorowskiego' ),
( 'Mogilany Osrodek Zdrowia' ),
( 'Wola Radziszowska Mala Ostra Gora' ),
( 'Mydlniki Granica Miasta' ),
( 'Tomaszowice Gliniki' ),
( 'Biezanow Potrzask' ),
( 'Szyce II' ),
( 'Mogilany Wlosan' ),
( 'Os.Jagiellonskie' ),
( 'Podleze Straz' ),
( 'Malborska' ),
( 'Bibice Petla' ),
( 'Owczary I' ),
( 'Babinskiego' ),
( 'Chalubinskiego' ),
( 'Przeginia Narodowa II' ),
( 'Elektromontaz' ),
( 'Kenara' ),
( 'Hallera' ),
( 'Plac Centralny im. R.Reagana' ),
( 'Trojadyn Skrzyzowanie' ),
( 'Wolowice Kapliczka' ),
( 'Muzeum Lotnictwa' ),
( 'Kopiec Kosciuszki' ),
( 'Karniowice I' ),
( 'Nowy Biezanow Poludnie' ),
( 'Rzozow Zagonnie' ),
( 'Chrosna Studnia' ),
( 'Ratajow Skrzyzowanie' ),
( 'Gorna Wies' ),
( 'Kamienskiego' ),
( 'Biezanow Szkola' ),
( 'Skawina Korabnicka' ),
( 'Balicka Wiadukt' ),
( 'Os.Mistrzejowice Nowe' ),
( 'Arka' ),
( 'Soltysowska Osiedle' ),
( 'Borek Falecki' ),
( 'Tyniec' ),
( 'Belwederczykow' ),
( 'Tonie Katy' ),
( 'Kosocicka' ),
( 'Kordylewskiego' ),
( 'Ks.laczka' ),
( 'Krzyszkowice Modrzewiowa' ),
( 'Radziszow Zadworze' ),
( 'Bedkowice Kawiory' ),
( 'Podgorki Skawinskie' ),
( 'Tonie' ),
( 'Slona Woda' ),
( 'Rzepakowa' ),
( 'Zagacie I' ),
( 'Wola Radziszowska Lipki' ),
( 'Siewna' ),
( 'Kopanka Szkola' ),
( 'Os.Na Skarpie' ),
( 'Tonie Skrzyzowanie' ),
( 'Marszowice Gory' ),
( 'Mlodziejowice Park' ),
( 'Klokoczyn' ),
( 'Cmentarz Podgorski' ),
( 'cwiklinskiej' ),
( 'Sudolska' ),
( 'Chelmonskiego Osiedle' ),
( 'Wegrzce Starostwo Powiatowe' ),
( 'Radziszow' ),
( 'Krowodrza Gorka' ),
( 'Kleeberga' ),
( 'Skawina Kopernika I' ),
( 'lutnia' ),
( 'Krzysztoforzyce Sklep' ),
( 'Skawina' ),
( 'Wlosan' ),
( 'Ludwinow' ),
( 'Kosmowskiej' ),
( 'swiatniki Gorne' ),
( 'Batalionu "Skala" AK' ),
( 'Skawina Popieluszki' ),
( 'Witosa' ),
( 'Ojcowska' ),
( 'Wieckowice' ),
( 'Os.Na Stoku Szkola' ),
( 'Bielany Szkola' ),
( 'Biezanow Trafo' ),
( 'Skawina Podbory' ),
( 'Zielonki UG' ),
( 'Os.Kliny' ),
( 'Aleja Przyjazni' ),
( 'Park Wodny' ),
( 'Prokocim' ),
( 'Rudawa Mlyn' ),
( 'Plaszow Szkola' ),
( 'Krzeslawice' ),
( 'Kolna' ),
( 'Zawiszy' ),
( 'Bosakow' ),
( 'Judyma' ),
( 'Koksochemia' ),
( 'Zaskale' ),
( 'Piekary I' ),
( 'Droga do Niegoszowic' ),
( 'Pasternik' ),
( 'Swoszowice Autostrada' ),
( 'Wesele' ),
( 'Mala Gora' ),
( 'Cholerzyn Granica' ),
( 'Sikorki' ),
( 'Jaskowice PKP' ),
( 'Rzebika' ),
( 'Mnikow Sklep' ),
( 'Liszki UG' ),
( 'Mlodziezy' ),
( 'Zelkow I' ),
( 'Plac Wszystkich swietych' ),
( 'Czyzyny' ),
( 'Kamienskiego Wiadukt' ),
( 'Zabierzow Dzialki' ),
( 'Piaszczysta' ),
( 'Wegrzce Wielkie III' ),
( 'Strzelcow' ),
( 'Sodfiny' ),
( 'Bosutow' ),
( 'Wyciaze Zachod' ),
( 'Bystronia' ),
( 'Os.Gorali' ),
( 'Dziady' ),
( 'Konopnickiej' ),
( 'Piekary Sklep' ),
( 'Cmentarz Rakowicki Zachod' ),
( 'Krzysztoforzyce przy Dworze' ),
( 'Wieclawice Stare' ),
( 'Skawina Rynek' ),
( 'Chalupki Gorne' ),
( 'Kabel' ),
( 'Golkowice' ),
( 'Jezynowa' ),
( 'Beblo Stara Wies' ),
( 'Kostrze' ),
( 'Truskawkowa' ),
( 'Reymana' ),
( 'Droga do Kaszowa' ),
( 'Bukow' ),
( 'Gaik' ),
( 'Modlniczka Trzcie' ),
( 'Salwator' ),
( 'Skawina Cmentarz' ),
( 'Dom Spokojnej Starosci' ),
( 'Teligi' ),
( 'Bronowice Wielkie' ),
( 'Krasnik' ),
( 'Glogera' ),
( 'Mydlniki Stawy' ),
( 'Grota-Roweckiego' ),
( 'Kocmyrzow' ),
( 'Gustawa Morcinka' ),
( 'Zelczyna Sklep' ),
( 'Rondo Barei' ),
( 'Wielkie Drogi Osrodek Zdrowia' ),
( 'Stella-Sawickiego' ),
( 'Slomniki Zagloby' ),
( 'Rzozow Baseny' ),
( 'Komuny Paryskiej' ),
( 'Kamien Dol' ),
( 'luczyce Zjawienie' ),
( 'Smardzowice IV' ),
( 'Ruszcza Cmentarz' ),
( 'Ruszcza' ),
( 'Kupaly' ),
( 'Jarzebiny' ),
( 'Zielonki Galicyjska' ),
( 'Wegrzce Blonie' ),
( 'Rzeszotary Polanki' ),
( 'Trojadyn Trafo' ),
( 'Os.lokietka' ),
( 'Trojanowice Strugi' ),
( 'Brzegi I' ),
( 'Plac Wolnica' ),
( 'Brzezie Kulka' ),
( 'DH Wanda' ),
( 'Suchy Jar' ),
( 'Prokocim Cmentarz' ),
( 'Zabierzow Mlyn' ),
( 'Os.Zlotego Wieku' ),
( 'Mackiewicza' ),
( 'Krowodrza Urzedy Skarbowe' ),
( 'Batowice' ),
( 'Dojazdow PKS' ),
( 'Wegrzce Wielkie' ),
( 'Sidzina' ),
( 'zyzna' ),
( 'Wadow Dzialki' ),
( 'Zelczyna I' ),
( 'Dabrowki I' ),
( 'Lesisko' ),
( 'Maslomiaca I' ),
( 'Trzecia Gora' ),
( 'Skawina Samborek Most' ),
( 'Makowa' ),
( 'Krzyszkowice Kosciol' ),
( 'Skawina Robotnicza' ),
( 'Dabie' ),
( 'Dauna' ),
( 'Wislicka' ),
( 'Habina' ),
( 'Krzysztoforzyce' ),
( 'Dworzec Glowny Zachod' ),
( 'Rybitwy Rozjazd' ),
( 'Marii Dabrowskiej' ),
( 'Wiktorowice Granica' ),
( 'Bedkowice Mosurowa' ),
( 'Niepolomice Moczydlo' ),
( 'Biezanow Cmentarz' ),
( 'Bulwarowa' ),
( 'Mogilany Rynek' ),
( 'Wola Zachariaszowska' ),
( 'Skrajna' ),
( 'Lusina Szkola' ),
( 'Czajowice' ),
( 'Rodzinna' ),
( 'luczyce Zwierzyniec' ),
( 'Czerwone Maki' ),
( 'Opolska Estakada' ),
( 'Lubocza Przychodnia' ),
( 'Skawina Energetykow' ),
( 'Os.Zgody' ),
( 'Lipka' ),
( 'Radziszow Za Mogilka' ),
( 'Batorego' ),
( 'Lubocza Trafo' ),
( 'Wawel' ),
( 'Niepolomice Batorego II' ),
( 'Leszka Bialego' ),
( 'Podleze Przedszkole' ),
( 'Rzeszotary' ),
( 'Zbydniowice' ),
( 'Raczna Podlas' ),
( 'Michalowice' ),
( 'Sucharskiego' ),
( 'Chmieleniec' ),
( 'sw.Gertrudy' ),
( 'Morawica Krzyzowka' ),
( 'Brzoskwinia Sklep' ),
( 'Tretowka' ),
( 'Michalowice Komora' ),
( 'Glogera Granica Miasta' ),
( 'Bedkowice' ),
( 'Kliny Zacisze' ),
( 'Rzepakowa swietlica' ),
( 'sciejowice Na Bagnach' ),
( 'Forteczna' ),
( 'Makowskiego' ),
( 'Szczyglice Autostrada' ),
( 'Jeziorzany' ),
( 'Szpital Okulistyczny' ),
( 'zywiecka' ),
( 'Wlotowa' ),
( 'Zagorzyce Stare' ),
( 'Kryspinow Sanka' ),
( 'Przylasek Rusiecki' ),
( 'Meissnera' ),
( 'Powstancow Wielkopolskich' ),
( 'Uniwersytet Rolniczy' ),
( 'Taklinskiego' ),
( 'Niepolomice Katek' ),
( 'Raczna I' ),
( 'Sulkowskiego' ),
( 'Czernichow' ),
( 'Os.Willowe' ),
( 'Soltysowska' ),
( 'Brzyczyna' ),
( 'Cystersow' ),
( 'Zelkow' ),
( 'Fort Winnica' ),
( 'Halszki' ),
( 'Skawina Nad Potokiem' ),
( 'Agatowa' ),
( 'Marcholta' ),
( 'Olsza II' ),
( 'Pruszynskiego' ),
( 'Podwierzbie' ),
( 'Sanka Skrzyzowanie' ),
( 'Nowy Biezanow' ),
( 'Olszanica Bory' ),
( 'Opatkowice Wiadukt' ),
( 'Skawina Korabniki' ),
( 'Ostafina' ),
( 'Liszki Krzyzowka' ),
( 'Wieliczka Park' ),
( 'Rybna II' ),
( 'Bibice' ),
( 'Zajezdnia Plaszow' ),
( 'Balice Grzybow' ),
( 'Teatr Bagatela' ),
( 'Kantorowice' ),
( 'Wegrzce Petla' ),
( 'Zielona Mala' ),
( 'Gospodarska' ),
( 'Krzeszowice' ),
( 'Wyki' ),
( 'Nowa Wies Jesionka' ),
( 'Wielkie Drogi Trzebol' ),
( 'Wieliczka Kopalnia Soli' ),
( 'Czyzyny Dworzec' ),
( 'Owczary Gajowa' ),
( 'Jugowicka' ),
( 'Skawina Pilsudskiego' ),
( 'Darwina' ),
( 'Wybickiego' ),
( 'Rzozow Szkola' ),
( 'Borkowska' ),
( 'Norymberska' ),
( 'Olszanica' ),
( 'Slomniki Osiedle' ),
( 'Goszyce Remiza' ),
( 'Wysylek' ),
( 'Stojalowskiego' ),
( 'Sieborowice' ),
( 'Nowa Wies Kapliczka' ),
( 'Blonia Koscielnickie' ),
( 'Skosna' ),
( 'Wieliczka Cmentarz' ),
( 'Nadbrzezie' ),
( 'Misnienska' ),
( 'Morawica Mostek' ),
( 'Beblo labajowa' ),
( 'Kobylany Remiza' ),
( 'Radziszow Stare Sanatorium' ),
( 'Gaj Szkola' ),
( 'Os.Kosciuszkowskie' ),
( 'Ratanice' ),
( 'Libertow Dolny' ),
( 'zerkowice Skrzyzowanie' ),
( 'Przegon' ),
( 'Brzeznica' ),
( 'Budzyn Zalew na Piaskach' ),
( 'Aleja 29 Listopada' ),
( 'Bolechowice' ),
( 'Konary Buk' ),
( 'Wielicka' ),
( 'Raczna Osiedle' ),
( 'Akacjowa' ),
( 'Rondo Czyzynskie' ),
( 'Garlica Murowana Kasztany' ),
( 'Zelkow Staw' ),
( 'Droga do Janowic' ),
( 'Rzeszotary Tempo' ),
( 'Burow' ),
( 'Rusocice Zaleg' ),
( 'Wola Batorska Cmentarz' ),
( 'Wegrzce Sudol' ),
( 'Powstancow Garaze' ),
( 'Mlynka I' ),
( 'Instytut Reumatologii' ),
( 'Wroblowice Cmentarz' ),
( 'Skawina 29 Listopada' ),
( 'Nowa Wies Kosciol' ),
( 'Przylasek Wyciaski' ),
( 'Wola Batorska Zamoglice' ),
( 'Banacha' ),
( 'Petrazyckiego' ),
( 'Radziszow Cmentarz' ),
( 'Brzezinka Zarzecze' ),
( 'Michalowka' ),
( 'Rzemieslnicza' ),
( 'Brzeska' ),
( 'Kaszow' ),
( 'Trojanowice' ),
( 'Pielgrzymowice II' ),
( 'Wieliczka' ),
( 'Garliczka Chochol' ),
( 'Skotniki' ),
( 'Skawina Radziszowska' ),
( 'lobzow PKP' ),
( 'Szymanskiego' ),
( 'Bartnicza' ),
( 'Wegrzce Sudol I' ),
( 'Klasztorna' ),
( 'Chalupki' ),
( 'Wzgorza Krzeslawickie' ),
( 'Rybitwy Sklep' ),
( 'Zelczyna Szkola' ),
( 'Kulerzow' ),
( 'Wrzasowice' ),
( 'Goszcza Cmentarz' ),
( 'Trojanowice I' ),
( 'Zakole' ),
( 'Czernichow GS' ),
( 'Morawica' ),
( 'Przeginia Duchowna Centrum' ),
( 'Raciborowice Centrum' ),
( 'Krzecin Czesna' ),
( 'Rusocice Jalowce' ),
( 'Morawica Cmentarz' ),
( 'Slomniki Rynek' ),
( 'Mlyn' ),
( 'Kasztanowa' ),
( 'Bulwarowa Ogrodki Dzialkowe' ),
( 'Ochojno Skrzyzowanie' ),
( 'Piekary III' ),
( 'Zawierzbie' ),
( 'Jordanowska' ),
( 'Zagrody' ),
( 'Polanowice Kolonia' ),
( 'Liszki I' ),
( 'Wadowska' ),
( 'lukasiewicza' ),
( 'Kokotow II' ),
( 'Katowicka' ),
( 'Czarnowiejska' ),
( 'luzycka' ),
( 'Zatyka' ),
( 'Hofmana' ),
( 'Batowice I' ),
( 'Oleandry' ),
( 'Malczewskiego' ),
( 'Szparagowa' ),
( 'Brzoskwinia Kamyk' ),
( 'Cholerzyn Skrzyzowanie' ),
( 'Agencja Krakow Wschod' ),
( 'Os.Na Stoku' ),
( 'UR Balicka' ),
( 'Cichy Kacik' ),
( 'Krasieniec' ),
( 'Grabie Polanka' ),
( 'Dworzec Glowny Wschod' ),
( 'Wrzasowice I' ),
( 'Ratanice I' ),
( 'Wilga' ),
( 'Piekary Gorne' ),
( 'Zablocie Koscielnickie' ),
( 'Fort Bodzow' ),
( 'Bacutil' ),
( 'Niepolomice Poreby' ),
( 'Hala Targowa' ),
( 'Bibice I' ),
( 'Zielinskiego' ),
( 'Kurdwanow Szkola' ),
( 'Skawina Kopernika' ),
( 'Ochodza Staw' ),
( 'Bosutow Krakowska' ),
( 'Bedkowice Borynia' ),
( 'Rzaska' ),
( 'Wlosan Krzyzowka' ),
( 'Kuznicy Kollatajowskiej' ),
( 'Zlocien' ),
( 'Batowice Kapliczka' ),
( 'Politechnika' ),
( 'Wyzral' ),
( 'Ruczaj' ),
( 'Polanowice' ),
( 'Krzecin Szkola' ),
( 'Pleszow' ),
( 'Winna Gora' ),
( 'Skawina Ajka' ),
( 'Wrozenice Gorka' ),
( 'Kakolowa' ),
( 'Powstancow' ),
( 'Uniwersytet Jagiellonski' ),
( 'Gora Borkowska' ),
( 'Rzaska Jednostka Wojskowa' ),
( 'Mazowiecka' ),
( 'Tomaszowice Wedonka' ),
( 'Radziszow Podlesie' ),
( 'Bibice Cmentarz' ),
( 'Swoszowice Pawilon' ),
( 'Rajsko' ),
( 'Balice OSP' ),
( 'Rzaska UR' ),
( 'Biezanow Granica Miasta' ),
( 'Wola Radziszowska' ),
( 'Biezanow Bazy' ),
( 'M1 Nowohucka' ),
( 'Sieroszewskiego' ),
( 'Wola Batorska zwirownia' ),
( 'Jeziorzany I' ),
( 'Winnicka' ),
( 'Jasienskiego' ),
( 'Kobylany' ),
( 'Suche Stawy' ),
( 'swiatniki Krakowska' ),
( 'Plk. Dabka' ),
( 'Szafranska' ),
( 'Aleja Roz' ),
( 'Niebieska Autostrada' ),
( 'swiatniki I' ),
( 'Ofiar Dabia' ),
( 'Zabawa' ),
( 'Chobot Lesniczowka' ),
( 'Przewoz' ),
( 'Beskidzka' ),
( 'Przy Kuzni' ),
( 'Ojcowska Dworek' ),
( 'Branice Osrodek Zdrowia' ),
( 'Os.Zielone' ),
( 'Wielka Wies' ),
( 'Piasta Kolodzieja' ),
( 'Skawina Starostwo Powiatowe' ),
( 'Skawina Szkola' ),
( 'Pasternik Cmentarz' ),
( 'Wolowice Szkola' ),
( 'Jana Kazimierza' ),
( 'Sidzina Olszyny' ),
( 'Radzikowskiego' ),
( 'Skawina Elektrownia' ),
( 'Oczyszczalnia sciekow "Kujawy"' ),
( 'Baba Jaga' ),
( 'Balice I' ),
( 'Zielona' ),
( 'Michalki' ),
( 'Bonarka' ),
( 'Radwanowice I' ),
( 'Olszanica Kapliczka' ),
( 'Modlniczka Mala' ),
( 'Szpital Narutowicza' ),
( 'Wadow Tunel' ),
( 'Park Decjusza' ),
( 'Malinowskiego' ),
( 'Radwanowice Petla' ),
( 'Krzecin' ),
( 'Kobierzyn' ),
( 'Kokotow I' ),
( 'Okulickiego' ),
( 'Mydlniki PKP' ),
( 'Maszyce Remiza' ),
( 'Podkamycze' ),
( 'Wielicka Granica Miasta' ),
( 'Mala Wies' ),
( 'Borek Szlachecki I' ),
( 'Kopalina' ),
( 'Podleze Balachowka' ),
( 'Skrzeszowice' ),
( 'Zelkow Wola' ),
( 'Spadochroniarzy' ),
( 'Rybitwy Dom Kultury' ),
( 'Wysiolek Luborzycki I' ),
( 'Gosciniec' ),
( 'Przybyslawice I' ),
( 'Brzozowka' ),
( 'Grabie Dom Kultury' ),
( 'Miechowity' ),
( 'Stoczniowcow' ),
( 'Skawina Wyspianskiego' ),
( 'Michalowice I' ),
( 'Zajezdnia Nowa Huta' ),
( 'Zbydniowice Szkola' ),
( 'Bronowice' ),
( 'Kocmyrzow Krzyzowka' ),
( 'Brzozowka Sklep' ),
( 'Brogi' ),
( 'Chelm' ),
( 'Igolomska' ),
( 'Raczna Kapliczka' ),
( 'Raczna Kosciol' ),
( 'Michalowice Banasiowka' ),
( 'Balice Autostrada' ),
( 'Brücknera' ),
( 'Swoszowice Poczta' ),
( 'Stawowa' ),
( 'Gromadzka' ),
( 'Odmetowa' ),
( 'Torfowa' ),
( 'Drozyska' ),
( 'Zielony Dol' ),
( 'Wola Luborzycka Las' ),
( 'Biskupinska' ),
( 'Walcownia' ),
( 'Wrzasowice Kowaleca' ),
( 'AWF' ),
( 'Wysiolek Luborzycki' ),
( 'Poczta Glowna' ),
( 'Szczegow' ),
( 'sw.Wawrzynca' ),
( 'Skawina PKP' ),
( 'Krzysztoforzyce Gora' ),
( 'Ksiecia Jozefa' ),
( 'Kleszczow' ),
( 'Skawina Koncentraty' ),
( 'Baluckiego' ),
( 'Lesmiana' ),
( 'Rzozow PKP' ),
( 'Przeginia Narodowa' ),
( 'swiatniki Cmentarz' ),
( 'Wola Batorska Kosciol' ),
( 'Os.Na Lotnisku' ),
( 'Kamien' ),
( 'lanowa' ),
( 'Kocmyrzow I' ),
( 'Wegrzynowicka' ),
( 'Rusocice I' ),
( 'Ukraina' ),
( 'Bolechowice I' ),
( 'Lasek Mogilski' ),
( 'Wyzral Wielka Droga' ),
( 'luczyce' ),
( 'Zabierzow I' ),
( 'Wolica Most' ),
( 'Biezanow' ),
( 'Zastow Dzialki' ),
( 'Dworzec Glowny' ),
( 'Mogilany Cmentarz' ),
( 'Warszowka' ),
( 'Wlosan Kopan' ),
( 'Krolowej Jadwigi' ),
( 'lowinskiego' ),
( 'Lubocza PKP' ),
( 'Konary I' ),
( 'Bolechowice II' ),
( 'Rybna Nowy swiat' ),
( 'Grabie' ),
( 'Rybna Zagorze' ),
( 'Bialopradnicka' ),
( 'Jerzmanowskiego' ),
( 'Trojanowice Petla' ),
( 'Kombinat' ),
( 'Rusocice leg' ),
( 'Chobot' ),
( 'Stare Wislisko' ),
( 'Swoszowice Osiedle' ),
( 'Opolska Kladka' ),
( 'Chrosna Sklep' ),
( 'Pytlasinskiego' ),
( 'Gorka Narodowa' ),
( 'Siewna Wiadukt' );

INSERT INTO Przystanki
VALUES
( 'Skalna' ),
( 'Ochojno Kamieniec' ),
( 'Michalowice Kozlica' ),
( 'Wyslouchow' ),
( 'Witkowice' ),
( 'Malborska Szkola' ),
( 'Lubocza Bugaj' ),
( 'Korzkiew II' ),
( 'Lusina Petla' ),
( 'Prokocim Rynek' ),
( 'Wyciaze' ),
( 'Czerwienskiego' ),
( 'Isep' ),
( 'Opolska' ),
( 'Sodfiny Kolonia' ),
( 'Uniwersytet Pedagogiczny' ),
( 'Wrzasowice II' ),
( 'Skawina Zachodnia' ),
( 'Skawina Cmentarz Komunalny' ),
( 'Michalowice Ogrodowa' ),
( 'Soboniowice' ),
( 'Branice' ),
( 'Prusy Szkola' ),
( 'Tomaszowice' ),
( 'Natansona' ),
( 'Conrada' ),
( 'Modlniczka Poligon' ),
( 'Wolowice' ),
( 'Libertow' ),
( 'Kaszow II' ),
( 'Jurczyce Dom Ludowy' ),
( 'Mogilany Wiadukt' ),
( 'luczanowice' ),
( 'Krzecin Cmentarz' ),
( 'Balice Lesna' ),
( 'Niepolomice Diesla' ),
( 'Rzaska Autostrada' ),
( 'Uniwersytet Ekonomiczny' ),
( 'Cmentarz Rakowicki' ),
( 'Wola Radziszowska leg' ),
( 'Turowicza' ),
( 'Instytut Pediatrii' ),
( 'Praska' ),
( 'Radziszow Kamionna' ),
( 'Brzeznica Kuznia' ),
( 'Giebultow Morgi' ),
( 'Grabie Kosciol' ),
( 'Weigla' ),
( 'Slomniki Kosciuszki' ),
( 'Wola Luborzycka' ),
( 'Skawina Tyniecka' ),
( 'Rzeszotary Trafo' ),
( 'Bienczycka' ),
( 'Ksiazniczki Las' ),
( 'Wielkie Drogi PKP' ),
( 'Ugorek' ),
( 'Wielkie Drogi Szkola' ),
( 'Karniow' ),
( 'Kopanka II' ),
( 'Wyciaze Sklep' ),
( 'Marszowice I' ),
( 'Rusocice Sklad' ),
( 'Fredry' ),
( 'Radziszow Wlosanka' ),
( 'Krzecin Kosciol' ),
( 'Poziomkowa' ),
( 'Goszyce' ),
( 'Os.Kurdwanow' ),
( 'Brozka' ),
( 'Marszowiec' ),
( 'Czernichow II' ),
( 'Krzyszkowice Os.Szymanowskiego' ),
( 'Bochenka' ),
( 'Leroy Merlin' ),
( 'Rzeszotary Panciawa' ),
( 'Wiklinowa' ),
( 'Bielanska' ),
( 'Architektow' ),
( 'Grebalow' ),
( 'Jurczyce Szkola' ),
( 'Nowolipki' ),
( 'Wola Radziszowska Chorzyny' ),
( 'Radziszow Podwale' ),
( 'Modlnica' ),
( 'Lekarska' ),
( 'Dworzec Plaszow' ),
( 'Nad Dlubnia' ),
( 'Tomaszowice I' ),
( 'Rzaka' ),
( 'luczanowice Skrzyzowanie' ),
( 'Wadow Szkola' ),
( 'Wegrzynowice Centrum' ),
( 'Kryspinow' ),
( 'Warchalowskiego' ),
( 'Mistrzejowice' ),
( 'Budzyn Zalew Budzynski' ),
( 'Cholerzyn' ),
( 'Czarnochowice I' ),
( 'Zabierzow Piekarnia' ),
( 'Balice Szkola' ),
( 'Wolica Kosciol' ),
( 'Urzad Marszalkowski' ),
( 'Jubilat' ),
( 'Ochojno Remiza' ),
( 'Garlica Duchowna Rozjazd' ),
( 'Wolica Sklep' ),
( 'Niedzwiedz PKP' ),
( 'Prosta' ),
( 'Pszona' ),
( 'Droga do Garliczki' ),
( 'lososkowice' ),
( 'Lasek legowski' ),
( 'Smardzowice' ),
( 'Lipowskiego' ),
( 'Muzeum Armii Krajowej' ),
( 'Rondo Ofiar Katynia' ),
( 'Zdrowa' ),
( 'Clepardia' ),
( 'Dabrowa Szlachecka Krzemiennik' ),
( 'sciejowice Granica' ),
( 'Wankowicza' ),
( 'Januszowice' ),
( 'Przeginia Duchowna' ),
( 'Zielonki Rozjazd' ),
( 'Aleksandrowice' ),
( 'Szczyglice' ),
( 'Wadow Os.Kolejowe' ),
( 'Barbary' ),
( 'Ochmanow Oknoplast' ),
( 'Krzyszkowice Kasztanowa II' ),
( 'Dabrowa Szlachecka' ),
( 'Slonecznikowa' ),
( 'Rondo Grzegorzeckie' ),
( 'Nowa Wies Szlachecka' ),
( 'Os.Marszowiec' ),
( 'Modlnica II' ),
( 'Zakliki' ),
( 'Stara Wola' ),
( 'Rondo Kocmyrzowskie im. Ks. Gorzelanego' ),
( 'Wola Radziszowska Most' ),
( 'Limanowskiego' ),
( 'Zabawa I' ),
( 'Goluchowice Sklep' ),
( 'Czulice I' ),
( 'Wegrzce Centrum Medyczne' ),
( 'Kapkazy' ),
( 'Wegrzynowice Dol' ),
( 'Smolenskiego' ),
( 'Rynek Debnicki' ),
( 'Trojadyn' ),
( 'Dworzec Towarowy' ),
( 'Zabierzow Gimnazjum' ),
( 'Klasztor Cystersow' ),
( 'Plac Inwalidow' ),
( 'Komorowskiego' ),
( 'Bujaka' ),
( 'Piekary II' ),
( 'Podgorki Tynieckie' ),
( 'Raczkiewicza' ),
( 'Rzeszotary Gorne' ),
( 'Wola Batorska Borek' ),
( 'Wilenska' ),
( 'Aleksandrowice Osiedle' ),
( 'swiatniki Centrum' ),
( 'Michalowice III' ),
( 'Wola Batorska Mikoniowiec' ),
( 'Os.Robotnicze' ),
( 'Szczecinska' ),
( 'Meksyk' ),
( 'Konary Sek' ),
( 'Rzozow Skotnica' ),
( 'Modlnica I Kolonia' ),
( 'Brzegi III' ),
( 'Dozynkowa' ),
( 'Kopanka Kapliczka' ),
( 'Jagielly' ),
( 'Na Krepaku' ),
( 'Bialy Kosciol' ),
( 'Rondo Piastowskie' ),
( 'Grebynice Mogielki' ),
( 'Bielany' ),
( 'Koscielniki' ),
( 'Pradnik Czerwony' ),
( 'Branice Pagorek' ),
( 'Judyma Szkola' ),
( 'Urzad Skarbowy Nowa Huta' ),
( 'Czernichow Bor' ),
( 'Olszanica Ogrodki Dzialkowe' ),
( 'Blokowa' ),
( 'Tondosa' ),
( 'Fiszera' ),
( 'Lusina Granica' ),
( 'Cracovia Blonia' ),
( 'Filharmonia' ),
( 'Chrosna Kapliczka' ),
( 'ZOO' ),
( 'Raczna II' ),
( 'Maly Plaszow' ),
( 'Nielepice Stadnina' ),
( 'Radziszow Zacisze' ),
( 'Opatkowice' ),
( 'Wodociagi' ),
( 'Niepolomice Podgrabie' ),
( 'Baczynskiego' ),
( 'Siejowka' ),
( 'Na Zaleczu' ),
( 'Zajezdnia Bienczyce' ),
( 'Barwna' ),
( 'Przybyslawice III' ),
( 'Prusy' ),
( 'Giebultow' ),
( 'Michalowice II' ),
( 'Przykopy' ),
( 'Lubocza Szkola' ),
( 'Kobierzynska' ),
( 'Kozierow Skrzyzowanie' ),
( 'Clo' ),
( 'Bukow Szkola' ),
( 'Rzozow I' ),
( 'Chabrowa' ),
( 'Radziszow Zawodzie' ),
( 'Rzeszotary Szkola' ),
( 'Janowka' ),
( 'Czulow II' ),
( 'Sulkow' ),
( 'Bielanskie Skaly' ),
( 'Kochanow' ),
( 'Pollanki' ),
( 'Zajezdnia Wola Duchacka' ),
( 'Cholerzyn Sklep' ),
( 'Miodowa' ),
( 'Krakow Arena' ),
( 'Radziszow Kladka' ),
( 'Dabrowa Szlachecka Krzyz' ),
( 'zelazowskiego' ),
( 'Drozdzowa' ),
( 'Cmentarz Batowice' ),
( 'Branice Na Dole' ),
( 'Goluchowice Jurczyce' ),
( 'Garlica Murowana' ),
( 'Cracovia' ),
( 'Zakonce' ),
( 'Gaj Zadziele' ),
( 'Pleszowska' ),
( 'Centrum JP II' ),
( 'Zabierzow Piaski' ),
( 'Niedzwiedz Felix' ),
( 'swidzinskiego' ),
( 'Dziekanowice Stacja Batowice' ),
( 'Niepolomice Wodna' ),
( 'Strzelnica' ),
( 'Przegorzaly' ),
( 'Glowackiego' ),
( 'Brzoskwinia' ),
( 'Kochanow I' ),
( 'Las Borkowski' ),
( 'Krasieniec Remiza' ),
( 'Niepolomice Rynek' ),
( 'Czulow' ),
( 'Resztowka' ),
( 'Witkowice Nowe' ),
( 'Stradom' ),
( 'Rudawa PKP' ),
( 'Niepolomice Wielicka' ),
( 'Ochodza' ),
( 'Branice Szkola' ),
( 'Lusina I' ),
( 'Aleksandry' ),
( 'Krzecin Sklep' ),
( 'Brodowicza' ),
( 'Gwarecka' ),
( 'Nowosadecka' ),
( 'Krzyszkowice Rozana' ),
( 'Skawina Podlipki' ),
( 'Mydlniki' ),
( 'Kopce' ),
( 'Czulowek' ),
( 'Modlniczka I' ),
( 'Krzemieniecka' ),
( 'Swoszowice Sklep' ),
( 'Liszki II' ),
( 'Libertow Zgodna' ),
( 'Wroblowice Szkola' ),
( 'Wola Radziszowska Podgazle' ),
( 'Zawila' ),
( 'Grotowa' ),
( 'Kostrze Kapliczka' ),
( 'sciejowice' ),
( 'Owczary Gorna' ),
( 'Modlnica Skrzyzowanie' ),
( 'Mrozowa' ),
( 'Borsucza' ),
( 'Grabowki' ),
( 'Piekary Palac' ),
( 'Krzeszowice Szkola' ),
( 'Szpital Rydygiera' ),
( 'Borki I' ),
( 'Smolki' ),
( 'Szczyglice Most' ),
( 'Wyciaska' ),
( 'Brzezie Narodowe' ),
( 'Zabierzow PKP' ),
( 'Wola Zachariaszowska Kresy' ),
( 'Landaua' ),
( 'Siwka' ),
( 'Wegrzce Magiczne Wzgorze' ),
( 'Krzecin Kapliczka' ),
( 'Kostrze Szkola' ),
( 'Konary Wlosan' ),
( 'Mogilany Cicha' ),
( 'Mlodziejowice Mlyn' ),
( 'Jezowa' ),
( 'Zeslawice Ogrodki Dzialkowe' ),
( 'Libertow Dzialy' ),
( 'Wrozenicka' ),
( 'Giebultow Plac Zabaw' ),
( 'Karowa' ),
( 'Wrozenice' ),
( 'Dabrowa' ),
( 'Tor Kajakowy' ),
( 'Balice II' ),
( 'Nowy Prokocim' ),
( 'Krakowka' ),
( 'Michalowice Lecznica' ),
( 'Tischnera' ),
( 'Tonie Gliniki' ),
( 'zerkowice Kolonia' ),
( 'Park Jordana' ),
( 'zeromskiego' ),
( 'Gielda Balicka P+R' ),
( 'Fort Mogila' ),
( 'Bogucianka' ),
( 'Zaklad Przerobki' ),
( 'Chorowice' ),
( 'Pychowice' ),
( 'Wola Batorska Ruskie' ),
( 'Kopiec Wandy' ),
( 'Orkana' ),
( 'Radziszow PKP' ),
( 'Balice Instytut' ),
( 'Slawka' ),
( 'Pisary Skrzyzowanie' ),
( 'Wroclawska' ),
( 'Wolowice III' ),
( 'Skrzyzowanie do Podchruscia' ),
( 'Marszowice' ),
( 'Olszecka' ),
( 'Kosocice' ),
( 'Rzepichy' ),
( 'Krasieniec Stary' ),
( 'Cmentarz Grebalow' ),
( 'Rybna I' ),
( 'Dojazdow Dzialki' ),
( 'Pilotow' ),
( 'Rudawa' ),
( 'Klimeckiego' ),
( 'Bunscha' ),
( 'Wola Duchacka' ),
( 'Hektary' ),
( 'Rybna Granica' ),
( 'Os.Strusia' ),
( 'Poroninska' ),
( 'Skawina Wojska Polskiego' ),
( 'Pekowice' ),
( 'Nawojowa Gora I' ),
( 'Wola Zabierzowska' ),
( 'Borek Szlachecki II' ),
( 'Korona' ),
( 'Zawila Cmentarz' ),
( 'Czulowek Kapliczka' ),
( 'leczycka' ),
( 'Lubicz' ),
( 'Borki' ),
( 'Ujazd Petla' ),
( 'Kocmyrzowska' ),
( 'Pradnicka' ),
( 'Luborzyca I' ),
( 'Niepolomice Jazy II' ),
( 'Zelkow II' ),
( 'Niepolomice Dworzec' ),
( 'Barycz' ),
( 'Karpinskiego' ),
( 'Miasteczko Studenckie AGH' ),
( 'Wiadukty' ),
( 'Dobrzyczany' ),
( 'Piasna Gorka' ),
( 'Maszyce Skrzyzowanie' ),
( 'Most Kotlarski' ),
( 'Radziszow Centrum' ),
( 'Wieliczka Rynek' ),
( 'Owczary Dluga' ),
( 'Albatrosow' ),
( 'Prusy WSR' ),
( 'Brzezie' ),
( 'Biezanow Pomnik' ),
( 'Kostrze OSP' ),
( 'Piekary' ),
( 'Bojki' ),
( 'Kujawy' ),
( 'Rondo Mlynskie' ),
( 'Kulerzow Wawoz' ),
( 'Raciborowice I' ),
( 'Wadow Glinik' ),
( 'Tyniec Kamieniolom' ),
( 'Krzeszowice Witaminka' ),
( 'Zablocie' ),
( 'Zabierzow Bochenski Centrum' ),
( 'Jurczyce Podole' ),
( 'Mlynka Petla' ),
( 'Aleja Waszyngtona' ),
( 'Iwanowice' ),
( 'Michalowice Las Michalowski' ),
( 'Biprostal' ),
( 'Rozyckiego' ),
( 'Biskupa Prandoty' ),
( 'Janasowka' ),
( 'Geologow' ),
( 'Jasnogorska' ),
( 'Grotowa I' ),
( 'Grebynice II' ),
( 'Brzoskwinia Koziary' ),
( 'Brzegi' ),
( 'Grebynice I' ),
( 'Nowa Wies' ),
( 'Pradnik Bialy Zachod' ),
( 'Grottgera' ),
( 'Zlocieniowa' ),
( 'Majora' ),
( 'Balice III' ),
( 'slosarczyka' ),
( 'Bosutow Dziekanowice' ),
( 'Armii Krajowej' ),
( 'Beblo Lasek' ),
( 'Garbarnia' ),
( 'Raciborowice' ),
( 'Przeginia Duchowna Bar' ),
( 'Niepolomice Batorego' ),
( 'Skawina Os.Radziszowskie' ),
( 'Wielkie Drogi' ),
( 'Wrzasowice Gorka' ),
( 'Opatkowice Zadworze' ),
( 'Soboniowice Granica Miasta' ),
( 'Dabrowa Szlachecka Figurka' ),
( 'Urzednicza' ),
( 'Borek Falecki I' ),
( 'Lipinskiego' ),
( 'Radziszow Lesniczowka' ),
( 'Park "Skaly Twardowskiego"' ),
( 'Skotniki Szkola' ),
( 'luczynskiego' ),
( 'Wrzasowice III' ),
( 'Rondo Hipokratesa' ),
( 'Zakrzow' ),
( 'lagiewniki' ),
( 'Sulechow' ),
( 'Puszkarska' ),
( 'Nowy Kleparz' ),
( 'Cechowa' ),
( 'Dunikowskiego' ),
( 'Fabryczna' ),
( 'Lusina Gorka' ),
( 'Francesco Nullo' ),
( 'Kruszwicka' ),
( 'Rondo Mogilskie' ),
( 'Gleboka' ),
( 'Zarzecze' ),
( 'Karniowice' ),
( 'Burow I' ),
( 'Piaski Nowe' ),
( 'Ks.Targosza' ),
( 'Zielonki Transformator' ),
( 'Ochodza Dom Ludowy' ),
( 'Krakow Business Park' ),
( 'Czulice' ),
( 'Rostworowskiego' ),
( 'Cracovia Stadion' ),
( 'Modlniczka' ),
( 'Bronowice Wiadukt' ),
( 'Bociana' ),
( 'Szczyglice Dom Kultury' ),
( 'Goszcza' ),
( 'Luborzyca' ),
( 'Gorka Pychowicka' ),
( 'Lusina Spacerowa' ),
( 'Lublanska' ),
( 'Krowoderskich Zuchow' ),
( 'Prokocim Szpital' ),
( 'Sucha' ),
( 'Lusina Dolna' ),
( 'Lajkonika' ),
( 'Brzezie Dzialki' ),
( 'Rynek Falecki' ),
( 'Cedynska' ),
( 'Rusocice II' ),
( 'Skawina Centrum Wodne' ),
( 'Szpital zeromskiego' ),
( 'Brzezinka' ),
( 'Rybna' ),
( 'zwirownia' ),
( 'Wieliczka Niepolomska' ),
( 'Bukow Klin' ),
( 'Rybna Dolna' ),
( 'Kuklinskiego' ),
( 'Kampus UJ' ),
( 'Dymarek' ),
( 'Kurdwanow' ),
( 'Dworcowa' ),
( 'Nad Drwina' ),
( 'Soltysowska Zaklady' ),
( 'Zabierzow Sklep' ),
( 'Piaski Wielkie' ),
( 'Centralna' ),
( 'Staniatki Wiadukt' ),
( 'Benedyktowicza' ),
( 'Elektrocieplownia Krakow' ),
( 'luczyce Las' ),
( 'Pradnik Bialy' ),
( 'Giebultow Zbiornik' ),
( 'Lindego' ),
( 'Wazewskiego' ),
( 'Zeslawice' ),
( 'Zdrojowa' ),
( 'Os.Dywizjonu 303' ),
( 'Boleslawa smialego' ),
( 'Skawina Rzepnik' ),
( 'Domagaly' ),
( 'Przybyszewskiego' ),
( 'Zagorzyce Dworskie' ),
( 'Ksiazniczki Centrum' ),
( 'Wadow' ),
( 'Brzoskwinia Gora' ),
( 'Trojadyn Szydlo' ),
( 'Wroblowice Rozwidlenie' ),
( 'Ciekowiec' ),
( 'Nawojowa Gora II' ),
( 'Solvay' ),
( 'Prokocim UJ' ),
( 'Dabrowki' ),
( 'Niepolomice Plaszowska I' ),
( 'Murownia' ),
( 'Basztowa LOT' ),
( 'Grabie Kuznia' ),
( 'Wegrzynowice' ),
( 'Sanktuarium Bozego Milosierdzia' ),
( 'Centrum Kongresowe' ),
( 'Kaszow Tyralowka' ),
( 'Lusina lany' ),
( 'Krakow Arena Al. Pokoju' ),
( 'Brama nr 5' ),
( 'Brama nr 4' ),
( 'Czernichow Stacja Paliw' ),
( 'Panienskich Skal' ),
( 'Libertow Krzyzowka' ),
( 'Bialucha' ),
( 'Krakow Airport T1' ),
( 'Wieliczka Kosciol' ),
( 'Wiktorowice Centrum' ),
( 'Wolica' ),
( 'Rakowicka' ),
( 'Garlica Duchowna' ),
( 'Szwedzka' ),
( 'Pod Lipa' ),
( 'Wegrzce Wielkie II' ),
( 'Maslomiaca' ),
( 'Zagacie II' ),
( 'Saska' ),
( 'Rusocice Wies' ),
( 'Biezanow Kaim' ),
( 'Kopanka Kosciol' ),
( 'Druzbackiej' ),
( 'Bronowice Male' ),
( 'Orzeszkowej' ),
( 'Krasnowolskiego' ),
( 'Bosutow Straz' ),
( 'Niepolomice Kosciuszki' ),
( 'Droga do Jeziorzan' ),
( 'Mlynka' ),
( 'Wrobela' ),
( 'Biezanowska' ),
( 'Zabierzow' ),
( 'Podstawie' );